import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Layout } from "@/components/layout";
import { AuthContextProvider } from "../context/use-auth-context";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full`}>
        <AuthContextProvider>
          {/* <Layout>{children}</Layout> */}
          <SidebarProvider
            style={
              {
                "--sidebar-width": "600px",
              } as React.CSSProperties
            }
          >
            <AppSidebar title="ACCREDIT" />
            {children}
          </SidebarProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
